// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjO2c74whzvpR_a7guFzL1Qr8KEwJb7_g',
    appId: '1:1062477056170:web:bb8e4d89dfc6b6a8f4e8d3',
    messagingSenderId: '1062477056170',
    projectId: 'paytrack-ff303',
    authDomain: 'paytrack-ff303.firebaseapp.com',
    storageBucket: 'paytrack-ff303.firebasestorage.app',
    measurementId: 'G-Y85QK24NPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkf5NLLfguwb2IGd7suG8fE17SojFqLE',
    appId: '1:1062477056170:android:57c749d12e75509bf4e8d3',
    messagingSenderId: '1062477056170',
    projectId: 'paytrack-ff303',
    storageBucket: 'paytrack-ff303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEbiwmPBrIY4benVd-UJsiSm2ZhmSiTU',
    appId: '1:1062477056170:ios:0eced127b45ef3fff4e8d3',
    messagingSenderId: '1062477056170',
    projectId: 'paytrack-ff303',
    storageBucket: 'paytrack-ff303.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhEbiwmPBrIY4benVd-UJsiSm2ZhmSiTU',
    appId: '1:1062477056170:ios:0eced127b45ef3fff4e8d3',
    messagingSenderId: '1062477056170',
    projectId: 'paytrack-ff303',
    storageBucket: 'paytrack-ff303.firebasestorage.app',
    iosBundleId: 'com.example.expenseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjO2c74whzvpR_a7guFzL1Qr8KEwJb7_g',
    appId: '1:1062477056170:web:616bf90a52be84bbf4e8d3',
    messagingSenderId: '1062477056170',
    projectId: 'paytrack-ff303',
    authDomain: 'paytrack-ff303.firebaseapp.com',
    storageBucket: 'paytrack-ff303.firebasestorage.app',
    measurementId: 'G-N2FCFZ94J3',
  );
}
